### PR TITLE
Appointment contact detail

### PR DESCRIPTION
**Pull request by elena-vi**

### CODE REVIEW

**Comment by elena-vi** [comment]
[Appointment Contact Details (MVP)](https://trello.com/c/hPiKAjFT/97-appointment-contact-details-mvp)

**Comment by elena-vi** [comment]
[Repair request confirmation contact details (MVP)](https://trello.com/c/r99AWVYs/99-repair-request-confirmation-contact-details-mvp)

**Comment by Bhavesh-Patel** [comment]
**Issue** 🐛 
When on the ["How should we confirm the appointment?"](https://purple-desert-05060ea03-31.westeurope.azurestaticapps.net/report-repair/contact-details) page, selecting either option and leaving the newly displayed input textbox blank and clicking `Continue` doesn't show validation error. The used is also not progressed on to the subsequent page.

**Steps to reproduce**
1. Step through pages entering appropriate details until ["How should we confirm the appointment?"](https://purple-desert-05060ea03-31.westeurope.azurestaticapps.net/report-repair/contact-details) page is displayed.
2. Click `Text Message (recommended)` or `Email` radio button.
3. Click `Continue` button.

**Expected**
Validation error displayed with appropriate message about missing data.

**Actual**
No visible change and not redirected to next page.

**Comment by Bhavesh-Patel** [comment]
**Issue 🐛**
When on the [What number should we call, if we need to get in touch?](https://purple-desert-05060ea03-31.westeurope.azurestaticapps.net/report-repair/contact-person) page with the cursor in the phone number input field, pressing up or down arrow keys changes the value entered respectively. If no value entered, '0' is assumed as the value and is incremented/decremented.

If the value has a prefix of '+', i.e. when specifying international dialling code, it is removed.
Equally, if the value is decremented below 0, an '-' is prefixed.

This is also the case for the phone number input field on [How should we confirm the appointment?](https://purple-desert-05060ea03-31.westeurope.azurestaticapps.net/report-repair/contact-details).

**Steps to reproduce**
1. Step through pages entering appropriate details until [What number should we call, if we need to get in touch?](https://purple-desert-05060ea03-31.westeurope.azurestaticapps.net/report-repair/contact-person) page is displayed.
2. Enter input field for entering a contact number.
3. Press up/down arrow keys.

**Expected**
Value is not changed. 
_Optional: Cursor should be relocated to beginning/end of textbox._

**Actual**
Value is incremented/decremented

**Review by Bhavesh-Patel — CHANGES_REQUESTED** [review]

**Review by Bhavesh-Patel — APPROVED** [review]

**Pull request merged**
